// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: exercises.sql

package db

import (
	"context"
	"database/sql"
)

const countExercisesCompleted = `-- name: CountExercisesCompleted :one
SELECT COUNT(DISTINCT exercise_id) FROM user_exercise_progress WHERE user_id = ?
`

func (q *Queries) CountExercisesCompleted(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExercisesCompleted, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalExercises = `-- name: CountTotalExercises :one
SELECT COUNT(*) FROM exercises
`

func (q *Queries) CountTotalExercises(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTotalExercises)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getExercise = `-- name: GetExercise :one
SELECT id, type, difficulty, prompt, correct_answer, options, hint, lesson_id, created_at FROM exercises WHERE id = ? LIMIT 1
`

func (q *Queries) GetExercise(ctx context.Context, id int64) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExercise, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Difficulty,
		&i.Prompt,
		&i.CorrectAnswer,
		&i.Options,
		&i.Hint,
		&i.LessonID,
		&i.CreatedAt,
	)
	return i, err
}

const getExerciseHistory = `-- name: GetExerciseHistory :many
SELECT uep.id, uep.user_id, uep.exercise_id, uep.is_correct, uep.user_answer, uep.completed_at, e.type, e.prompt FROM user_exercise_progress uep
JOIN exercises e ON e.id = uep.exercise_id
WHERE uep.user_id = ?
ORDER BY uep.completed_at DESC
LIMIT ?
`

type GetExerciseHistoryParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
}

type GetExerciseHistoryRow struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	ExerciseID  int64          `json:"exercise_id"`
	IsCorrect   int64          `json:"is_correct"`
	UserAnswer  sql.NullString `json:"user_answer"`
	CompletedAt string         `json:"completed_at"`
	Type        string         `json:"type"`
	Prompt      string         `json:"prompt"`
}

func (q *Queries) GetExerciseHistory(ctx context.Context, arg GetExerciseHistoryParams) ([]GetExerciseHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getExerciseHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExerciseHistoryRow{}
	for rows.Next() {
		var i GetExerciseHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseID,
			&i.IsCorrect,
			&i.UserAnswer,
			&i.CompletedAt,
			&i.Type,
			&i.Prompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercises = `-- name: ListExercises :many
SELECT id, type, difficulty, prompt, hint, lesson_id, created_at FROM exercises ORDER BY id
`

type ListExercisesRow struct {
	ID         int64          `json:"id"`
	Type       string         `json:"type"`
	Difficulty string         `json:"difficulty"`
	Prompt     string         `json:"prompt"`
	Hint       sql.NullString `json:"hint"`
	LessonID   sql.NullInt64  `json:"lesson_id"`
	CreatedAt  string         `json:"created_at"`
}

func (q *Queries) ListExercises(ctx context.Context) ([]ListExercisesRow, error) {
	rows, err := q.db.QueryContext(ctx, listExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExercisesRow{}
	for rows.Next() {
		var i ListExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Difficulty,
			&i.Prompt,
			&i.Hint,
			&i.LessonID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercisesByDifficulty = `-- name: ListExercisesByDifficulty :many
SELECT id, type, difficulty, prompt, hint, lesson_id, created_at FROM exercises WHERE difficulty = ? ORDER BY id
`

type ListExercisesByDifficultyRow struct {
	ID         int64          `json:"id"`
	Type       string         `json:"type"`
	Difficulty string         `json:"difficulty"`
	Prompt     string         `json:"prompt"`
	Hint       sql.NullString `json:"hint"`
	LessonID   sql.NullInt64  `json:"lesson_id"`
	CreatedAt  string         `json:"created_at"`
}

func (q *Queries) ListExercisesByDifficulty(ctx context.Context, difficulty string) ([]ListExercisesByDifficultyRow, error) {
	rows, err := q.db.QueryContext(ctx, listExercisesByDifficulty, difficulty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExercisesByDifficultyRow{}
	for rows.Next() {
		var i ListExercisesByDifficultyRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Difficulty,
			&i.Prompt,
			&i.Hint,
			&i.LessonID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercisesByType = `-- name: ListExercisesByType :many
SELECT id, type, difficulty, prompt, hint, lesson_id, created_at FROM exercises WHERE type = ? ORDER BY id
`

type ListExercisesByTypeRow struct {
	ID         int64          `json:"id"`
	Type       string         `json:"type"`
	Difficulty string         `json:"difficulty"`
	Prompt     string         `json:"prompt"`
	Hint       sql.NullString `json:"hint"`
	LessonID   sql.NullInt64  `json:"lesson_id"`
	CreatedAt  string         `json:"created_at"`
}

func (q *Queries) ListExercisesByType(ctx context.Context, type_ string) ([]ListExercisesByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listExercisesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExercisesByTypeRow{}
	for rows.Next() {
		var i ListExercisesByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Difficulty,
			&i.Prompt,
			&i.Hint,
			&i.LessonID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercisesByTypeAndDifficulty = `-- name: ListExercisesByTypeAndDifficulty :many
SELECT id, type, difficulty, prompt, hint, lesson_id, created_at FROM exercises WHERE type = ? AND difficulty = ? ORDER BY id
`

type ListExercisesByTypeAndDifficultyParams struct {
	Type       string `json:"type"`
	Difficulty string `json:"difficulty"`
}

type ListExercisesByTypeAndDifficultyRow struct {
	ID         int64          `json:"id"`
	Type       string         `json:"type"`
	Difficulty string         `json:"difficulty"`
	Prompt     string         `json:"prompt"`
	Hint       sql.NullString `json:"hint"`
	LessonID   sql.NullInt64  `json:"lesson_id"`
	CreatedAt  string         `json:"created_at"`
}

func (q *Queries) ListExercisesByTypeAndDifficulty(ctx context.Context, arg ListExercisesByTypeAndDifficultyParams) ([]ListExercisesByTypeAndDifficultyRow, error) {
	rows, err := q.db.QueryContext(ctx, listExercisesByTypeAndDifficulty, arg.Type, arg.Difficulty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExercisesByTypeAndDifficultyRow{}
	for rows.Next() {
		var i ListExercisesByTypeAndDifficultyRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Difficulty,
			&i.Prompt,
			&i.Hint,
			&i.LessonID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordExerciseAttempt = `-- name: RecordExerciseAttempt :exec
INSERT INTO user_exercise_progress (user_id, exercise_id, is_correct, user_answer) VALUES (?, ?, ?, ?)
`

type RecordExerciseAttemptParams struct {
	UserID     int64          `json:"user_id"`
	ExerciseID int64          `json:"exercise_id"`
	IsCorrect  int64          `json:"is_correct"`
	UserAnswer sql.NullString `json:"user_answer"`
}

func (q *Queries) RecordExerciseAttempt(ctx context.Context, arg RecordExerciseAttemptParams) error {
	_, err := q.db.ExecContext(ctx, recordExerciseAttempt,
		arg.UserID,
		arg.ExerciseID,
		arg.IsCorrect,
		arg.UserAnswer,
	)
	return err
}
