// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: flashcards.sql

package db

import (
	"context"
)

const countCardsInDeck = `-- name: CountCardsInDeck :one
SELECT COUNT(*) FROM flashcards WHERE deck_id = ?
`

func (q *Queries) CountCardsInDeck(ctx context.Context, deckID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardsInDeck, deckID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDueFlashcards = `-- name: CountDueFlashcards :one
SELECT COUNT(*)
FROM flashcards f
LEFT JOIN user_flashcard_progress ufp ON ufp.flashcard_id = f.id AND ufp.user_id = ?
WHERE ufp.next_review_date IS NULL OR ufp.next_review_date <= datetime('now')
`

func (q *Queries) CountDueFlashcards(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDueFlashcards, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReviewLog = `-- name: CreateReviewLog :exec
INSERT INTO review_log (user_id, flashcard_id, quality) VALUES (?, ?, ?)
`

type CreateReviewLogParams struct {
	UserID      int64 `json:"user_id"`
	FlashcardID int64 `json:"flashcard_id"`
	Quality     int64 `json:"quality"`
}

func (q *Queries) CreateReviewLog(ctx context.Context, arg CreateReviewLogParams) error {
	_, err := q.db.ExecContext(ctx, createReviewLog, arg.UserID, arg.FlashcardID, arg.Quality)
	return err
}

const getDueFlashcards = `-- name: GetDueFlashcards :many
SELECT f.id, f.deck_id, f.front, f.back, f.created_at
FROM flashcards f
LEFT JOIN user_flashcard_progress ufp ON ufp.flashcard_id = f.id AND ufp.user_id = ?1
WHERE (ufp.next_review_date IS NULL OR ufp.next_review_date <= datetime('now'))
ORDER BY ufp.next_review_date ASC
LIMIT ?2
`

type GetDueFlashcardsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
}

func (q *Queries) GetDueFlashcards(ctx context.Context, arg GetDueFlashcardsParams) ([]Flashcard, error) {
	rows, err := q.db.QueryContext(ctx, getDueFlashcards, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flashcard{}
	for rows.Next() {
		var i Flashcard
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDueFlashcardsByDeck = `-- name: GetDueFlashcardsByDeck :many
SELECT f.id, f.deck_id, f.front, f.back, f.created_at
FROM flashcards f
LEFT JOIN user_flashcard_progress ufp ON ufp.flashcard_id = f.id AND ufp.user_id = ?1
WHERE f.deck_id = ?2 AND (ufp.next_review_date IS NULL OR ufp.next_review_date <= datetime('now'))
ORDER BY ufp.next_review_date ASC
LIMIT ?3
`

type GetDueFlashcardsByDeckParams struct {
	UserID int64 `json:"user_id"`
	DeckID int64 `json:"deck_id"`
	Limit  int64 `json:"limit"`
}

func (q *Queries) GetDueFlashcardsByDeck(ctx context.Context, arg GetDueFlashcardsByDeckParams) ([]Flashcard, error) {
	rows, err := q.db.QueryContext(ctx, getDueFlashcardsByDeck, arg.UserID, arg.DeckID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flashcard{}
	for rows.Next() {
		var i Flashcard
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlashcard = `-- name: GetFlashcard :one
SELECT id, deck_id, front, back, created_at FROM flashcards WHERE id = ? LIMIT 1
`

func (q *Queries) GetFlashcard(ctx context.Context, id int64) (Flashcard, error) {
	row := q.db.QueryRowContext(ctx, getFlashcard, id)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.CreatedAt,
	)
	return i, err
}

const getFlashcardDeck = `-- name: GetFlashcardDeck :one
SELECT id, name, description, created_at FROM flashcard_decks WHERE id = ? LIMIT 1
`

func (q *Queries) GetFlashcardDeck(ctx context.Context, id int64) (FlashcardDeck, error) {
	row := q.db.QueryRowContext(ctx, getFlashcardDeck, id)
	var i FlashcardDeck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getFlashcardProgress = `-- name: GetFlashcardProgress :one
SELECT id, user_id, flashcard_id, repetitions, easiness_factor, interval_days, next_review_date, last_reviewed_at FROM user_flashcard_progress WHERE user_id = ? AND flashcard_id = ? LIMIT 1
`

type GetFlashcardProgressParams struct {
	UserID      int64 `json:"user_id"`
	FlashcardID int64 `json:"flashcard_id"`
}

func (q *Queries) GetFlashcardProgress(ctx context.Context, arg GetFlashcardProgressParams) (UserFlashcardProgress, error) {
	row := q.db.QueryRowContext(ctx, getFlashcardProgress, arg.UserID, arg.FlashcardID)
	var i UserFlashcardProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FlashcardID,
		&i.Repetitions,
		&i.EasinessFactor,
		&i.IntervalDays,
		&i.NextReviewDate,
		&i.LastReviewedAt,
	)
	return i, err
}

const getReviewHistory = `-- name: GetReviewHistory :many
SELECT rl.id, rl.user_id, rl.flashcard_id, rl.quality, rl.reviewed_at, f.front, f.back FROM review_log rl
JOIN flashcards f ON f.id = rl.flashcard_id
WHERE rl.user_id = ?
ORDER BY rl.reviewed_at DESC
LIMIT ?
`

type GetReviewHistoryParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
}

type GetReviewHistoryRow struct {
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
	FlashcardID int64  `json:"flashcard_id"`
	Quality     int64  `json:"quality"`
	ReviewedAt  string `json:"reviewed_at"`
	Front       string `json:"front"`
	Back        string `json:"back"`
}

func (q *Queries) GetReviewHistory(ctx context.Context, arg GetReviewHistoryParams) ([]GetReviewHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getReviewHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReviewHistoryRow{}
	for rows.Next() {
		var i GetReviewHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FlashcardID,
			&i.Quality,
			&i.ReviewedAt,
			&i.Front,
			&i.Back,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlashcardDecks = `-- name: ListFlashcardDecks :many
SELECT id, name, description, created_at FROM flashcard_decks ORDER BY id
`

func (q *Queries) ListFlashcardDecks(ctx context.Context) ([]FlashcardDeck, error) {
	rows, err := q.db.QueryContext(ctx, listFlashcardDecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlashcardDeck{}
	for rows.Next() {
		var i FlashcardDeck
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFlashcardProgress = `-- name: UpsertFlashcardProgress :exec
INSERT INTO user_flashcard_progress (user_id, flashcard_id, repetitions, easiness_factor, interval_days, next_review_date, last_reviewed_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, datetime('now'))
ON CONFLICT(user_id, flashcard_id) DO UPDATE SET
    repetitions = ?3,
    easiness_factor = ?4,
    interval_days = ?5,
    next_review_date = ?6,
    last_reviewed_at = datetime('now')
`

type UpsertFlashcardProgressParams struct {
	UserID         int64   `json:"user_id"`
	FlashcardID    int64   `json:"flashcard_id"`
	Repetitions    int64   `json:"repetitions"`
	EasinessFactor float64 `json:"easiness_factor"`
	IntervalDays   int64   `json:"interval_days"`
	NextReviewDate string  `json:"next_review_date"`
}

func (q *Queries) UpsertFlashcardProgress(ctx context.Context, arg UpsertFlashcardProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertFlashcardProgress,
		arg.UserID,
		arg.FlashcardID,
		arg.Repetitions,
		arg.EasinessFactor,
		arg.IntervalDays,
		arg.NextReviewDate,
	)
	return err
}
