// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: grammar.sql

package db

import (
	"context"
)

const countCompletedLessons = `-- name: CountCompletedLessons :one
SELECT COUNT(*) FROM user_grammar_progress WHERE user_id = ? AND completed = 1
`

func (q *Queries) CountCompletedLessons(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompletedLessons, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalLessons = `-- name: CountTotalLessons :one
SELECT COUNT(*) FROM grammar_lessons
`

func (q *Queries) CountTotalLessons(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTotalLessons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGrammarExamples = `-- name: GetGrammarExamples :many
SELECT id, lesson_id, spanish, english, explanation, sort_order FROM grammar_examples WHERE lesson_id = ? ORDER BY sort_order
`

func (q *Queries) GetGrammarExamples(ctx context.Context, lessonID int64) ([]GrammarExample, error) {
	rows, err := q.db.QueryContext(ctx, getGrammarExamples, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GrammarExample{}
	for rows.Next() {
		var i GrammarExample
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Spanish,
			&i.English,
			&i.Explanation,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGrammarLessonBySlug = `-- name: GetGrammarLessonBySlug :one
SELECT id, title, slug, summary, content, sort_order, created_at FROM grammar_lessons WHERE slug = ? LIMIT 1
`

func (q *Queries) GetGrammarLessonBySlug(ctx context.Context, slug string) (GrammarLesson, error) {
	row := q.db.QueryRowContext(ctx, getGrammarLessonBySlug, slug)
	var i GrammarLesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.Content,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getUserGrammarProgress = `-- name: GetUserGrammarProgress :one
SELECT id, user_id, lesson_id, completed, completed_at FROM user_grammar_progress WHERE user_id = ? AND lesson_id = ? LIMIT 1
`

type GetUserGrammarProgressParams struct {
	UserID   int64 `json:"user_id"`
	LessonID int64 `json:"lesson_id"`
}

func (q *Queries) GetUserGrammarProgress(ctx context.Context, arg GetUserGrammarProgressParams) (UserGrammarProgress, error) {
	row := q.db.QueryRowContext(ctx, getUserGrammarProgress, arg.UserID, arg.LessonID)
	var i UserGrammarProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LessonID,
		&i.Completed,
		&i.CompletedAt,
	)
	return i, err
}

const listGrammarLessons = `-- name: ListGrammarLessons :many
SELECT id, title, slug, summary, sort_order, created_at FROM grammar_lessons ORDER BY sort_order
`

type ListGrammarLessonsRow struct {
	ID        int64  `json:"id"`
	Title     string `json:"title"`
	Slug      string `json:"slug"`
	Summary   string `json:"summary"`
	SortOrder int64  `json:"sort_order"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) ListGrammarLessons(ctx context.Context) ([]ListGrammarLessonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGrammarLessons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrammarLessonsRow{}
	for rows.Next() {
		var i ListGrammarLessonsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGrammarProgress = `-- name: ListUserGrammarProgress :many
SELECT lesson_id, completed FROM user_grammar_progress WHERE user_id = ?
`

type ListUserGrammarProgressRow struct {
	LessonID  int64 `json:"lesson_id"`
	Completed int64 `json:"completed"`
}

func (q *Queries) ListUserGrammarProgress(ctx context.Context, userID int64) ([]ListUserGrammarProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserGrammarProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserGrammarProgressRow{}
	for rows.Next() {
		var i ListUserGrammarProgressRow
		if err := rows.Scan(&i.LessonID, &i.Completed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGrammarProgress = `-- name: UpsertGrammarProgress :exec
INSERT INTO user_grammar_progress (user_id, lesson_id, completed, completed_at)
VALUES (?, ?, 1, datetime('now'))
ON CONFLICT(user_id, lesson_id) DO UPDATE SET completed = 1, completed_at = datetime('now')
`

type UpsertGrammarProgressParams struct {
	UserID   int64 `json:"user_id"`
	LessonID int64 `json:"lesson_id"`
}

func (q *Queries) UpsertGrammarProgress(ctx context.Context, arg UpsertGrammarProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertGrammarProgress, arg.UserID, arg.LessonID)
	return err
}
