// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Exercise struct {
	ID            int64          `json:"id"`
	Type          string         `json:"type"`
	Difficulty    string         `json:"difficulty"`
	Prompt        string         `json:"prompt"`
	CorrectAnswer string         `json:"correct_answer"`
	Options       sql.NullString `json:"options"`
	Hint          sql.NullString `json:"hint"`
	LessonID      sql.NullInt64  `json:"lesson_id"`
	CreatedAt     string         `json:"created_at"`
}

type Flashcard struct {
	ID        int64  `json:"id"`
	DeckID    int64  `json:"deck_id"`
	Front     string `json:"front"`
	Back      string `json:"back"`
	CreatedAt string `json:"created_at"`
}

type FlashcardDeck struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   string         `json:"created_at"`
}

type GrammarExample struct {
	ID          int64          `json:"id"`
	LessonID    int64          `json:"lesson_id"`
	Spanish     string         `json:"spanish"`
	English     string         `json:"english"`
	Explanation sql.NullString `json:"explanation"`
	SortOrder   int64          `json:"sort_order"`
}

type GrammarLesson struct {
	ID        int64  `json:"id"`
	Title     string `json:"title"`
	Slug      string `json:"slug"`
	Summary   string `json:"summary"`
	Content   string `json:"content"`
	SortOrder int64  `json:"sort_order"`
	CreatedAt string `json:"created_at"`
}

type ReviewLog struct {
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
	FlashcardID int64  `json:"flashcard_id"`
	Quality     int64  `json:"quality"`
	ReviewedAt  string `json:"reviewed_at"`
}

type Session struct {
	Token     string `json:"token"`
	UserID    int64  `json:"user_id"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type User struct {
	ID        int64  `json:"id"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type UserExerciseProgress struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	ExerciseID  int64          `json:"exercise_id"`
	IsCorrect   int64          `json:"is_correct"`
	UserAnswer  sql.NullString `json:"user_answer"`
	CompletedAt string         `json:"completed_at"`
}

type UserFlashcardProgress struct {
	ID             int64          `json:"id"`
	UserID         int64          `json:"user_id"`
	FlashcardID    int64          `json:"flashcard_id"`
	Repetitions    int64          `json:"repetitions"`
	EasinessFactor float64        `json:"easiness_factor"`
	IntervalDays   int64          `json:"interval_days"`
	NextReviewDate string         `json:"next_review_date"`
	LastReviewedAt sql.NullString `json:"last_reviewed_at"`
}

type UserGrammarProgress struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	LessonID    int64          `json:"lesson_id"`
	Completed   int64          `json:"completed"`
	CompletedAt sql.NullString `json:"completed_at"`
}

type VocabularyWord struct {
	ID              int64          `json:"id"`
	Spanish         string         `json:"spanish"`
	English         string         `json:"english"`
	PartOfSpeech    sql.NullString `json:"part_of_speech"`
	Category        sql.NullString `json:"category"`
	ExampleSentence sql.NullString `json:"example_sentence"`
	CreatedAt       string         `json:"created_at"`
}
