// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: vocabulary.sql

package db

import (
	"context"
	"database/sql"
)

const getRandomVocabulary = `-- name: GetRandomVocabulary :many
SELECT id, spanish, english, part_of_speech, category, example_sentence, created_at FROM vocabulary_words ORDER BY RANDOM() LIMIT ?
`

func (q *Queries) GetRandomVocabulary(ctx context.Context, limit int64) ([]VocabularyWord, error) {
	rows, err := q.db.QueryContext(ctx, getRandomVocabulary, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VocabularyWord{}
	for rows.Next() {
		var i VocabularyWord
		if err := rows.Scan(
			&i.ID,
			&i.Spanish,
			&i.English,
			&i.PartOfSpeech,
			&i.Category,
			&i.ExampleSentence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomVocabularyByCategory = `-- name: GetRandomVocabularyByCategory :many
SELECT id, spanish, english, part_of_speech, category, example_sentence, created_at FROM vocabulary_words WHERE category = ? ORDER BY RANDOM() LIMIT ?
`

type GetRandomVocabularyByCategoryParams struct {
	Category sql.NullString `json:"category"`
	Limit    int64          `json:"limit"`
}

func (q *Queries) GetRandomVocabularyByCategory(ctx context.Context, arg GetRandomVocabularyByCategoryParams) ([]VocabularyWord, error) {
	rows, err := q.db.QueryContext(ctx, getRandomVocabularyByCategory, arg.Category, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VocabularyWord{}
	for rows.Next() {
		var i VocabularyWord
		if err := rows.Scan(
			&i.ID,
			&i.Spanish,
			&i.English,
			&i.PartOfSpeech,
			&i.Category,
			&i.ExampleSentence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabulary = `-- name: ListVocabulary :many
SELECT id, spanish, english, part_of_speech, category, example_sentence, created_at FROM vocabulary_words ORDER BY category, spanish
`

func (q *Queries) ListVocabulary(ctx context.Context) ([]VocabularyWord, error) {
	rows, err := q.db.QueryContext(ctx, listVocabulary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VocabularyWord{}
	for rows.Next() {
		var i VocabularyWord
		if err := rows.Scan(
			&i.ID,
			&i.Spanish,
			&i.English,
			&i.PartOfSpeech,
			&i.Category,
			&i.ExampleSentence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabularyByCategory = `-- name: ListVocabularyByCategory :many
SELECT id, spanish, english, part_of_speech, category, example_sentence, created_at FROM vocabulary_words WHERE category = ? ORDER BY spanish
`

func (q *Queries) ListVocabularyByCategory(ctx context.Context, category sql.NullString) ([]VocabularyWord, error) {
	rows, err := q.db.QueryContext(ctx, listVocabularyByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VocabularyWord{}
	for rows.Next() {
		var i VocabularyWord
		if err := rows.Scan(
			&i.ID,
			&i.Spanish,
			&i.English,
			&i.PartOfSpeech,
			&i.Category,
			&i.ExampleSentence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabularyCategories = `-- name: ListVocabularyCategories :many
SELECT DISTINCT category FROM vocabulary_words WHERE category IS NOT NULL ORDER BY category
`

func (q *Queries) ListVocabularyCategories(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listVocabularyCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var category sql.NullString
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
